cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
	path('', views.home_page, name='home_page'),
    path('gioithieu', views.gioi_thieu, name='gioi_thieu'),
    path('lienhe', views.lien_he, name='lien_he'),
	path('<slug:slug>', views.product_detail, name='product_detail'),
	path('add/favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
	path('remove/favorites/<int:product_id>/', views.remove_from_favorites, name='remove_from_favorites'),
	path('favorites/', views.favorites, name='favorites'),
	path('search/', views.search, name='search'),
	path('filter/<slug:slug>/', views.filter_by_category, name='filter_by_category'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify


class Category(models.Model):
    title = models.CharField(max_length=200)
    sub_category = models.ForeignKey(
        'self', on_delete=models.CASCADE,
        related_name='sub_categories', null=True, blank=True
    )
    is_sub = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs): # new
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
        

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    image = models.ImageField(upload_to='products')
    title = models.CharField(max_length=250)
    description = models.TextField()
    price = models.IntegerField()
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return self.slug
        
    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator

from shop.models import Product, Category
from cart.forms import QuantityForm


def paginat(request, list_objects):
	p = Paginator(list_objects, 20)
	page_number = request.GET.get('page')
	try:
		page_obj = p.get_page(page_number)
	except PageNotAnInteger:
		page_obj = p.page(1)
	except EmptyPage:
		page_obj = p.page(p.num_pages)
	return page_obj


def home_page(request):
	products = Product.objects.all()
	context = {'products': paginat(request ,products)}
	return render(request, 'home_page.html', context)

def gioi_thieu(request):
	products = Product.objects.all()
	context = {'products': paginat(request ,products)}
	return render(request, 'gioi_thieu.html', context)

def lien_he(request):
	products = Product.objects.all()
	context = {'products': paginat(request ,products)}
	return render(request, 'lien_he.html', context)

def product_detail(request, slug):
	form = QuantityForm()
	product = get_object_or_404(Product, slug=slug)
	related_products = Product.objects.filter(category=product.category).all()[:5]
	context = {
		'title':product.title,
		'product':product,
		'form':form,
		'favorites':'favorites',
		'related_products':related_products
	}
	if request.user.likes.filter(id=product.id).first():
		context['favorites'] = 'remove'
	return render(request, 'product_detail.html', context)


@login_required
def add_to_favorites(request, product_id):
	product = get_object_or_404(Product, id=product_id)
	request.user.likes.add(product)
	return redirect('shop:product_detail', slug=product.slug)


@login_required
def remove_from_favorites(request, product_id):
	product = get_object_or_404(Product, id=product_id)
	request.user.likes.remove(product)
	return redirect('shop:favorites')


@login_required
def favorites(request):
	products = request.user.likes.all()
	context = {'title':'Favorites', 'products':products}
	return render(request, 'favorites.html', context)


def search(request):
	query = request.GET.get('q')
	products = Product.objects.filter(title__icontains=query).all()
	context = {'products': paginat(request ,products)}
	return render(request, 'home_page.html', context)


def filter_by_category(request, slug):
	"""when user clicks on parent category
	we want to show all products in its sub-categories too
	"""
	result = []
	category = Category.objects.filter(slug=slug).first()
	[result.append(product) \
		for product in Product.objects.filter(category=category.id).all()]
	# check if category is parent then get all sub-categories
	if not category.is_sub:
		sub_categories = category.sub_categories.all()
		# get all sub-categories products
		for category in sub_categories:
			[result.append(product) \
				for product in Product.objects.filter(category=category).all()]
	context = {'products': paginat(request ,result)}
	return render(request, 'home_page.html', context)

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Bạt xếp Khải Nhân</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Yummy
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center me-auto me-lg-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>KHẢI NHÂN<span>.</span></h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'shop:home_page' %}">Trang Chủ</a></li>
          <li><a href="{% url 'shop:gioi_thieu' %}">Giới Thiệu</a></li>
          <li class="dropdown"><a href="#"><span>Sản Phẩm</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a href="{% url 'shop:lien_he' %}">Liên Hệ</a></li>
        </ul>
      </nav><!-- .navbar -->
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Mái Hiên Di Động - Khải Nhân</h2>
          {% block menu %} {% endblock %}
        </div>

      </div>
    </div><!-- End Breadcrumbs -->

    <section class="sample-page">
      <div class="container" data-aos="fade-up">
        {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
      <!-- content -->
      {% block content %}{% endblock %}
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div>
            <h4>Địa chỉ</h4>
            <p>
              154/1/10 Trần Thị Trọng<br>
              Phường 15, quận Tân Bình, tp.HCM<br>
            </p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Liên hệ</h4>
            <p>
              <strong>Điện Thoại:</strong> 0907 408 003<br>
              <strong>Email:</strong> maihiendidongkhainhan@gmail.com<br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Giờ làm việc</h4>
            <p>
              <strong>T2-T7: 7:00 Sáng - 19:00 Chiều</strong>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Liên hệ</h4>
          <div class="social-links d-flex">
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Hiển Phạm</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>
<div class="float-contact">
  <div class="face">
      <a href="https://www.facebook.com/maihiendidongkhainhan" target="blank">
          <img alt="facebook" src="{% static 'assets/img/Facebook_icon.png' %}" style="width: 40px; height: 40px;" />
      </a>
  </div>

  <div class="chat-face">
      <a href="https://www.messenger.com/t/maihiendidongkhainhan" target="blank">
          <img alt="messenger" src="{% static 'assets/img/messenger-icon.png' %}" style="width: 40px; height: 40px;" />
      </a>
  </div>

  <div class="zalo">
      <a href="https://zalo.me/0907408003" target="blank">
          <img alt="zalo" src="{% static 'assets/img/zalo-icon.png' %}" style="width: 40px; height: 40px;" />
      </a>
  </div>

  <div class="hotline">
      <a href="tel:0907408003">
          <img alt="hotline" src="{% static 'assets/img/phone-icon.png' %}" style="width: 40px; height: 40px;" />
      </a>
  </div>
</div>


<style type="text/css">


@media (min-width: 1025px) {
.float-contact {
  position: fixed;
  bottom: 40px;
  right: 40px;
  z-index: 99999;
  text-align: left;
}
.chat-face, .hotline, .zalo, .face {
  overflow: hidden;
  border: none !important;
  background: none !important;
}
.chat-face a, .hotline a, .zalo a, .face a {
  display: block;
  margin-bottom: 6px;
}
.chat-face a:hover, .hotline a:hover, .zalo a:hover, .face a:hover {
  background: #137b00;
  color: #fff;
  text-decoration: none;
}
.chat-face a img, .hotline a img, .zalo a img, .face a img {
  display: block;
  margin: auto;
}
.chat-face a, .hotline a, .zalo a, .face a {
  color: #000;
  text-align: center;
  display: block;
  font-size: 10px;
}
}

@media (max-width: 1024px) {
.float-contact {
  position: fixed;
  bottom: 0px;
  z-index: 99999;
  display: flex;
  background: linear-gradient(#fff,#137b00);
  width: 100%;
  height: 63px;
}
.face, .chat-face, .zalo, .hotline {
  width: 25%;
  text-align: center;
  margin: auto;
  border-left: 1px solid #fff;
  border-right: 1px solid #fff;
}
.face a img, .chat-face a img, .zalo a img, .hotline a img {
  display: block;
  margin: 5px auto 5px;
}
.face a, .chat-face a, .zalo a, .hotline a {
  color: #fff;
  font-size: 13px;
}
}
</style>

</html>

shop/templates/favorites.html
{% extends 'base.html' %}
{% block content %}
{% if products %}
<h2>Your Favorites</h2>
<hr>
{% for product in products %}
<div class="card me-2 mb-2" style="width: 16rem;">
  <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ product.image.url }}">
  <div class="mt-3 text-center">
    <h5 class="card-title">{{ product.title }}</h5>
    <p class="text-muted">${{ product.price }}</p>
    <a href="{{ product.get_absolute_url }}" class="mb-3 btn btn-primary w-100">Buy Now</a>
  </div>
  <a href="{% url 'shop:remove_from_favorites' product.id %}" class="mb-3 btn btn-outline-danger">Remove</a>
</div>
{% endfor %}
{% else %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 mt-5 pt-5 text-center">
    <br>
    <h3 class="text-muted text-capitalize">favorites list is empty..!</h3>
    <a href="/" class="text-primary text-decoration-none">Back</a>
  </div>
  <div class="col-md-2"></div>
</div>
{% endif %}
{% endblock %}

shop/templates/gioi_thieu.html
{% extends 'base.html' %}


{% block menu %}
<ol>
  <li><a href="home_page.html">Trang Chủ</a></li>
  <li>Giới Thiệu</li>
</ol>
{% endblock %}

{% block content %}
<div id="primary" class="content-area primary">
  <main id="main" class="site-main">
    <article class="post-145 page type-page status-publish ast-article-single" id="post-145" itemtype="https://schema.org/CreativeWork" itemscope="itemscope">
        <div class="entry-content clear" itemprop="text">
          <p style="text-align: justify;">Xin kính chào quý khách hàng,</p>
          <p style="text-align: justify;">Công ty TNHH Xây dựng TMDV Khải Nhân chúng tôi là đơn vị chuyên cung cấp các loại bạt che nắng mưa chuyên dụng, chuyên thi công lắp đặt các sản phẩm:</p>
          <ul style="text-align: justify;">
            <li>Mái hiên di động</li>
            <li>Mái che di động</li>
            <li>Mái xếp di động</li>
            <li>Mái che thông minh</li>
            <li>Bạt che nắng mưa</li>
            <li>Dù che nắng các loại</li>
          </ul>
          <p style="text-align: justify;">Chúng tôi hoạt động với phương châm luôn lắng nghe và đặt quyền lợi của khách hàng lên trên hết. Vì chúng tôi hiểu rằng, chỉ khi làm việc vì khách hàng, khách hàng mới tin tưởng và đồng hành cùng mái xếp Khải Nhân trong thời gian dài.</p>
          <p style="text-align: justify;">Đến với mái xếp Khải Nhân, khách hàng sẽ luôn nhận được sự tư vấn, hỗ trợ tận tình, chu đáo. Chúng tôi sở hữu đội ngũ nhân viên dày dặn kinh nghiệm, am hiểu kỹ thuật, chắc chắn sẽ giúp khách hàng có được sản phẩm mái hiên di động, mái che di động, mái xếp di động, bạt che nắng mưa các loại chất lượng, ưng ý nhất!</p>
          <p>Mọi chi tiết xin vui lòng liên hệ:</p>
          <p><span style="color: #0000ff;"><a style="color: #0000ff;" href="{% url 'shop:home_page' %}"><strong>Công ty TNHH Xây dựng TMDV Khải Nhân</strong></a></span></p>
          <ul>
            <li>Địa chỉ: Hoàng Diệu, Chương Mỹ, Hà Nội</li>
            <li>Mã số thuế: 0109757694</li>
            <li>Hotline: 0973 883 992</li>
            <li><span class="">Email:</span> maihiendidongkhainhan@gmail.com</li>
          </ul>
          <p>
      </div><!-- .entry-content .clear -->



    </article>
  </main>
</div>
{% endblock %}

shop/templates/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block menu %}
<ol>
  <li><a href="home_page.html">Trang Chủ</a></li>
</ol>
{% endblock %}

{% block content %}
<div id="primary" class="content-area primary">
  <main id="main" class="site-main">
    <article class="post-260 page type-page status-publish has-post-thumbnail ast-article-single" id="post-260" itemtype="https://schema.org/CreativeWork" itemscope="itemscope">


      <div class="entry-content clear" itemprop="text">


        <p style="text-align: center;">Mái hiên di động Khải Nhân chuyên cung cấp bạt mái che, mái hiên, mái xếp, bạt che nắng mưa giá rẻ! Khách hàng có nhu cầu mua bạt che nắng, bạt mái hiên, bạt mái xếp, bạt mái che chất lượng tốt hoặc muốn lắp đặt mái hiên di động, mái che di động, mái xếp di động giá rẻ, hãy liên hệ với chúng tôi để nhận ưu đãi mới nhất!</p>
      <p></p>
      <p>&nbsp;</p>
      <h2>Hệ thống phân phối bạt mái che nắng mưa giá rẻ trên toàn quốc</h2>
      <p>Chúng tôi cam kết cung cấp sản phẩm bạt che nắng, mành che nắng, bạt xanh cam:</p>
      <ul>
      <li>Chất lượng tốt, mẫu mã đẹp, đa dạng chủng loại, nguồn gốc xuất xứ rõ ràng.</li>
      <li>Sản phẩm bảo hành lên đến 36 tháng, hỗ trợ nhiệt tình trước, trong và sau quá trình mua hàng.</li>
      <li>Giá thành cạnh tranh, nhiều ưu đãi hấp dẫn cho khách hàng mua số lượng lớn!</li>
      </ul>
      <h2>Nhận lắp đặt mái hiên di động, mái che di động, mái xếp di động chất lượng, giá rẻ!</h2>
      <p>Khi lựa chọn Mái hiên di động Khải Nhân, khách hàng sẽ nhận được:</p>
      <ul>
      <li>Dịch vụ lắp đặt mái hiên di động, mái xếp di động, mái che di động nhanh chóng, nhiệt tình, chuyên nghiệp.</li>
      <li>Bạt che nhập khẩu từ Đài Loan, Hàn Quốc, Nhật, Úc, Mỹ,…cam kết khả năng che chắn nắng mưa, cách nhiệt, chống nóng lên đến 90%.</li>
      <li>Giá lắp đặt mái hiên, mái che, mái xếp được tính trọn gói, không thu thêm phụ phí!</li>
      <li>Lắp đặt theo yêu cầu, với đội ngũ nhân viên kỹ thuật nhiều năm kinh nghiệm, đảm bảo đúng an toàn kỹ thuật, chắc chắn, bền đẹp.</li>
      </ul>
      <p><img decoding="async" loading="lazy" class="aligncenter" src="{% static 'assets/img/bang_hieu.jpg' %}" alt="mái hiên di động" width="869" height="376"/></p>
      <p>Mọi chi tiết xin vui lòng liên hệ:</p>
      <p><strong>Công ty TNHH Xây dựng TMDV Khải Nhân</strong></p>
      <ul>
      <li>Địa chỉ: Phường 15, Tân Bình, thành phố Hồ Chí Minh</li>
      <li>Hotline: 0907 408 003</li>
      <li>Email:&nbsp;maihiendidongkhainhan@gmail.com</li>
      </ul>
      </div><!-- .entry-content .clear -->
    </article>
  </main>
</div>
{% endblock %}

shop/templates/lien_he.html
{% extends 'base.html' %}


{% block menu%}
<ol>
  <li><a href="home_page.html">Trang Chủ</a></li>
  <li>Liên Hệ</li>
</ol>
{% endblock %}


{% block content %}
<div id="primary" class="content-area primary">
  <main id="main" class="site-main">
    <article class="post-146 page type-page status-publish ast-article-single" id="post-146" itemtype="https://schema.org/CreativeWork" itemscope="itemscope">
      <div class="entry-content clear" itemprop="text">


        <p style="text-align: justify;">Trong quá trình tham khảo sản phẩm, sử dụng các sản phẩm của bạt mái xếp Khải Nhân như: mái hiên di động, mái che di động, mái xếp di động, các loại bạt che nắng mưa chuyên dụng,&#8230;khách hàng cần tư vấn thêm, hãy liên hệ với chúng tôi qua địa chỉ:</p>
      <p><strong>Công ty TNHH Xây dựng TMDV Khải Nhân</strong></p>
      <ul>
      <li>Địa chỉ: Hoàng Diệu, Chương Mỹ, Hà Nội</li>
      <li>Mã số: 0109757694</li>
      <li>Hotline: 0973 883 992</li>
      <li><i class=" icofont-email"></i><span class="">Email:</span> batmaixep@gmail.com</li>
      </ul>
      <p>Hệ thống chi nhánh:</p>
      <ul>
      <li>Chi nhánh 1: Số 59, Tổ 3, Văn Nội, Phú Lương, Hà Đông</li>
      <li>Chi nhánh 2: Thôn Thạch Điền, Thạch Hà, Hà Tĩnh</li>
      <li>Chi nhánh 3: Đường D8, KDC Thuận Giao, Thuận An, Bình Dương</li>
      <li>Chi nhánh 4: 440 Đặng Thúc Vịnh, Ấp 1, xã Đông Thạnh, Hóc Môn, Tp. HCM</li>
      </ul>



      </div><!-- .entry-content .clear -->



    </article>
  </main>
</div>
{% endblock %}

shop/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-3 mt-4">
    <div class="col-md-1"></div>
    <!-- product content -->
    <div class="col-md-5 p-3 border rounded">
        <!-- category -->
        <div class="border-bottom mb-2 pb-2">
            <span class="text-muted ">categories:</span><a class="text-decoration-none text-dark" href="{% url 'shop:filter_by_category' product.category.slug %}"> {{product.category}}</a>
        </div>
        <!-- title -->
        <h2>{{ product.title }}</h2>
        <!-- price -->
        <h4 class="mt-4 text-dark">Price: ${{ product.price }}</h4>
        <!-- description -->
        <div class="mt-4 pe-3 mb-5">{{ product.description }}</div>
        <!-- cart btn -->
        <form method="post" action="{% url 'cart:add_to_cart' product.id %}">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn btn-primary mt-4" value="Add to cart">
        </form>
        <br>
        {% if favorites == 'remove' %}
        <a href="{% url 'shop:remove_from_favorites' product.id %}" class="btn btn-outline-danger mt-5 text-capitalize ">{{favorites}} from favorites</a>
        {% else %}
        <a href="{% url 'shop:add_to_favorites' product.id %}" class="btn btn-outline-success mt-5 text-capitalize ">add to {{favorites}}</a>
        {% endif %}
    </div>
    <!-- product image -->
    <div class="col-md-6">
        <img style="object-fit: cover;" class="rounded" src="{{ product.image.url }}" width="510" height="500">
    </div>
</div>
<!-- related products -->
<div class="row mt-4 mb-4">
    <h3>Related Products:</h3><hr>
    {% for p in related_products %}
        <!-- dont show the current product in this page -->
        {% if p != product %}
            <div class="card me-2 mb-2" style="width: 16rem;">
                <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ p.image.url }}">
                <div class="mt-3 text-center">
                <h5 class="card-title">{{ p.title }}</h5>
                <p class="text-muted">${{ p.price }}</p>
                <a href="{{ p.get_absolute_url }}" class="mb-3 btn btn-outline-primary w-100">Buy Now</a>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}